# Note that only one of these targets is required

bigquery:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: training-user-1-project
      dataset: dbt_dataset # You can also use "schema" here
      threads: 1
